### ISSUE TITLE
Modi Error Msg during Add on install

### ISSUE THREAD

**Issue by nchauley** [RunasSudo/plugin.video.cntv-live#25]
Get error msg that AddOn does not have correct structure

**Comment by RunasSudo** [comment]
It works for me. Can you try installing it from the [xbmc-addons-chinese](https://github.com/taxigps/xbmc-addons-chinese) repo?

**Comment by nchauley** [comment]
Hi there - thx for your response! Repo and add on install was successful however get “Channel Unavailable” on every channel, any time of day, when I try to stream from CNTV video add on (CCTV 1 - 13, BTV etc). 
Ever since CNTV reverted to Akamai based HLS stream, CCTV channels have been unavailable. 

Any other suggestions? You assistance and response is greatly appreciated…Thx

**Comment by RunasSudo** [comment]
Thanks for your response. I was unaware that CNTV had reverted to Akamai HDS/HLS streams. I will fix this as soon as possible.
