### ISSUE TITLE
Development still active?

### ISSUE THREAD

**Issue by Connum** [RunasSudo/plugin.video.cntv-live#27]
Hi,

Is there still active development going on? Currently, only CCTV-1, the variations of CCTV-4 and CCTV-NEWS are working, none of the other channels does (neither in the National Channels category nor in any of the others.

Any help?

**Comment by RunasSudo** [comment]
This plugin behaves like an iOS/Android device to stream video from the [CNTV website](http://tv.cntv.cn/live/). Unfortunately, a while ago, CNTV made some changes which broke this, encouraging users to switch to CBox, their app-based platform. I haven't the effort to work out how to integrate this plugin with the new format, so right now only channels that can be streamed on an iOS/Android device via a web browser from the [CNTV website](http://tv.cntv.cn/live/) can be viewed.
